### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by alxgord** [ArTTo8/2048#1]
- [ ] Добавить проверку возможности хода
- [ ] Динамически генерировать значение клетки
- [ ] Сообщение о конце игры
